default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET

default_tests:
    path: /tests
    defaults: { _controller: "AppBundle:Default:tests" }
    methods: POST

default_login:
    path: /login
    defaults: { _controller: "AppBundle:Default:login" }
    methods: POST