user_new:
    path: /new
    defaults: { _controller: "AppBundle:User:new" }
    methods: POST

user_edit:
    path: /edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods: POST

user_detail:
    path: /detail/{id}
    defaults: { _controller: "AppBundle:Default:userDetail", id:null }
    methods: POST